{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime-ktx",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.5.0.aar",
          "url": "navigation-runtime-ktx-2.5.0.aar",
          "size": 1770,
          "sha512": "04c50ffb668ae95bd8bbdb3266ee90f27d0997d19efaddd34077f498e3a5310bfd5c407bee02af6b0ac7ea260f81489c524bb369a961b4d3c801801c5b32b061",
          "sha256": "815f96b5e62dd56d43971a9aa20e61639c13d5e393ff6c84f124dba2c9656976",
          "sha1": "2d2f61735479180f71877182dfb08a0ae80e5c4e",
          "md5": "c8ddc2a49840ae9c607a17dae9bcf67c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.5.0.aar",
          "url": "navigation-runtime-ktx-2.5.0.aar",
          "size": 1770,
          "sha512": "04c50ffb668ae95bd8bbdb3266ee90f27d0997d19efaddd34077f498e3a5310bfd5c407bee02af6b0ac7ea260f81489c524bb369a961b4d3c801801c5b32b061",
          "sha256": "815f96b5e62dd56d43971a9aa20e61639c13d5e393ff6c84f124dba2c9656976",
          "sha1": "2d2f61735479180f71877182dfb08a0ae80e5c4e",
          "md5": "c8ddc2a49840ae9c607a17dae9bcf67c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-ktx-2.5.0-sources.jar",
          "url": "navigation-runtime-ktx-2.5.0-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}