{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common-ktx",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.5.0.aar",
          "url": "navigation-common-ktx-2.5.0.aar",
          "size": 1771,
          "sha512": "1b7bafe17dec9ac6c3a7e04fae9dd10fa1f72efac21d53e1c643e733aa6490fdade169ebe6e11bb9cad531fa78de5f3e0dbe7153bc82978b336f7313d6ab6a2d",
          "sha256": "364b3132b4f925c05ade091e7f3dc8ce45f57c4da320b56a4739eb7bfffc25b4",
          "sha1": "2e9d0287d82446e3c0eefae8d85e76880eafb60f",
          "md5": "766dd0bd8e588070b7342ac855f2c7ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.5.0.aar",
          "url": "navigation-common-ktx-2.5.0.aar",
          "size": 1771,
          "sha512": "1b7bafe17dec9ac6c3a7e04fae9dd10fa1f72efac21d53e1c643e733aa6490fdade169ebe6e11bb9cad531fa78de5f3e0dbe7153bc82978b336f7313d6ab6a2d",
          "sha256": "364b3132b4f925c05ade091e7f3dc8ce45f57c4da320b56a4739eb7bfffc25b4",
          "sha1": "2e9d0287d82446e3c0eefae8d85e76880eafb60f",
          "md5": "766dd0bd8e588070b7342ac855f2c7ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-ktx-2.5.0-sources.jar",
          "url": "navigation-common-ktx-2.5.0-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}