{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.5.0.aar",
          "url": "navigation-runtime-2.5.0.aar",
          "size": 121098,
          "sha512": "29e62e8778db1c707d1fd49a03a7e413a88ea6acffd36db94e340bf473e1f759adfd813b82ce34af61cce081870ad2a2cf15878c05336cca0e44e012c9dd4b25",
          "sha256": "6b42423369973b6ad714465d01ae0e103595fd9729dc338e1262773516892bdf",
          "sha1": "6bc9da7f3d3f65e654c0789ef06e42576f6730ed",
          "md5": "ff6a3132343b523021945368154e796a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.5.0.aar",
          "url": "navigation-runtime-2.5.0.aar",
          "size": 121098,
          "sha512": "29e62e8778db1c707d1fd49a03a7e413a88ea6acffd36db94e340bf473e1f759adfd813b82ce34af61cce081870ad2a2cf15878c05336cca0e44e012c9dd4b25",
          "sha256": "6b42423369973b6ad714465d01ae0e103595fd9729dc338e1262773516892bdf",
          "sha1": "6bc9da7f3d3f65e654c0789ef06e42576f6730ed",
          "md5": "ff6a3132343b523021945368154e796a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-2.5.0-sources.jar",
          "url": "navigation-runtime-2.5.0-sources.jar",
          "size": 46530,
          "sha512": "e32bf9b29cb38ecc24b23712689224cc7179293cde095ac8748b7e2c02786280a33b9dc71f26add95838e84d7cf5e14e6889ac1565116a506ad8e339df311089",
          "sha256": "ac066753327766f1a151ab3e8f7b9136e5c006a551398b256eff16c660439047",
          "sha1": "fbf2621a7c1cb8f21baedebccc884425e8e2e996",
          "md5": "ef4dd50dcc1d35271a7fc75915dc965f"
        }
      ]
    }
  ]
}