{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-compose",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.5.0.aar",
          "url": "navigation-compose-2.5.0.aar",
          "size": 1095739,
          "sha512": "a6e5bf1459d994e15265fc0512c14a558a9c9ccfa52917194837ec9425f613f8162bf20ebf7ff1b10550e05441b9c47f65cb43f002dc36c40d8702d945442220",
          "sha256": "bb8d9c406fe4283ce4dab50f8c87b27507c29bffc9b8deff1b421b6e05729ad6",
          "sha1": "c6ec3ec3dc519c8be8754d44895427fec1d4e91f",
          "md5": "564cb2332eb46c4d3e9c639c387fcfb9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.5.0.aar",
          "url": "navigation-compose-2.5.0.aar",
          "size": 1095739,
          "sha512": "a6e5bf1459d994e15265fc0512c14a558a9c9ccfa52917194837ec9425f613f8162bf20ebf7ff1b10550e05441b9c47f65cb43f002dc36c40d8702d945442220",
          "sha256": "bb8d9c406fe4283ce4dab50f8c87b27507c29bffc9b8deff1b421b6e05729ad6",
          "sha1": "c6ec3ec3dc519c8be8754d44895427fec1d4e91f",
          "md5": "564cb2332eb46c4d3e9c639c387fcfb9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-compose-2.5.0-sources.jar",
          "url": "navigation-compose-2.5.0-sources.jar",
          "size": 10998,
          "sha512": "74fc7e04fe39d90cfc265654cc0b55b20f1ab3d80ab4ad81d58729cf937188a1cd9dc3e8bb53dc054ec61333406354acb7e3d42e4281e2c082e57a37cb749f06",
          "sha256": "f91b4a3ccd95974562d6b56004310e4d32ce2f107f302e815a73ea41da4601d6",
          "sha1": "8b1dd15fa0586e9f0850d9a3e3ece7bec443a75a",
          "md5": "8db21b74d722c7d7e7c866b240daa1cf"
        }
      ]
    }
  ]
}